name: cinemapedia_app
description: "Una aplicación en flutter para ver la cartelera del cine"
publish_to: 'none'
version: 1.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  analyzer: ^5.13.0
  animate_do: ^3.3.4
  card_swiper: ^3.0.1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.4.0
  flutter_riverpod: ^2.5.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^13.2.4
  google_mobile_ads: ^5.1.0
  intl: ^0.19.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.3
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  package_rename: ^1.7.0

package_rename_config:
  android:
    app_name: Cinemapedia TZ
    package_name: com.juancarlostz.cinemapedia_tz
    # override_old_package: com.example.example
    lang: kotlin

  ios:
    app_name: Cinemapedia TZ
    bundle_name: Cinamepedia TZ
    package_name: com.juancarlostz.cinemapediatz

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app-icon-1.jpeg"
  image_path_android: "assets/icon/app-icon-2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  color: "#252829"
  # color_android: "#252829"
  # image_ios: assets/icon/app-icon-2.png
  # ios_content_mode: center
  android_12:
    color: "#252829"
  image: assets/icon/app-icon-2.png # Ruta a la imagen del splash screen.
  android: true # Habilita el splash screen para Android.
  ios: true # Habilita el splash screen para iOS.
  # color_ios: "#42a5f5"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icon/
